# Generated by Django 4.1.7 on 2023-03-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_preparatio_steps_is_html_recipe_preparation_steps_is_html_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_steps_is_html',
            new_name='preparatio_steps_is_html',
        ),
    ]
