# Generated by Django 4.1.7 on 2023-03-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_preparation_steps_is_html_recipe_preparatio_steps_is_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparatio_steps_is_html',
            new_name='preparation_steps_is_html',
        ),
    ]
